dist: bionic

before_install:
  - gem install package_cloud

script:
  - tar cfJ Source.tar.xz Luv Wallpapers
  - wget -q https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - export UPLOADTOOL_SUFFIX=$TRAVIS_BRANCH
  - bash upload.sh Source.tar.xz
  - rm Source.tar.xz
  - sudo ./travis-build.sh
  - package_cloud push nitrux/repo/debian/trixie *.deb

branches:
  only:
    - master

deploy:
  - provider: script
    script: wget -qO - https://raw.githubusercontent.com/Nitrux/nitrux-repository-util/master/upload-pkgs | sh -s *.deb
    skip_cleanup: true
    on:
      branch: master

notifications:
  email: false
